dependencies:
- name: mariadb
  version: 4.x.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mariadb.enabled
- name: elasticsearch
  version: 1.13.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: elasticsearch.enabled
