
# These variables are build-specific and should be passed via the --set parameter.
nginx:
  image: 'you need to pass in a value for nginx.image to your helm chart'
drupal:
  image: 'you need to pass in a value for drupal.image to your helm chart'
  env:
  #these are added to drupal environment
    PHP_FPM_CLEAR_ENV: "no"

mariadb:
  persistence:
    storageClass: standard
  replication:
    enabled: false

  db:
    name: drupal
    user: drupal

ingress:
  hostname: "silta.wdr.io"
