
nginx:
  image: 'ignore, overridden at build time'
drupal:
  image: 'ignore, overridden at build time'

mariadb:
  persistence:
    storageClass: standard
  replication:
    enabled: false

  db:
    name: drupal
    user: drupal

ingress:
  hostname: "silta.wdr.io"
