apiVersion: v1
kind: Service
metadata:
  name: drupal-drupal
  labels:
    app: drupal
spec:
  ports:
    - port: 80
  selector:
    app: drupal
    tier: drupal
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: drupal-drupal
  labels:
    app: drupal
spec:
  selector:
    matchLabels:
      app: drupal
      tier: drupal
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        tier: drupal
    spec:
      containers:
      - image: sergejss/reponame:1
        name: drupal
        env:
        - name: PHP_FPM_CLEAR_ENV
          value: "no"
        - name: DB_USER_DRUPAL
          value: drupal
        - name: DB_NAME_DRUPAL
          value: drupal
        - name: DB_HOST_DRUPAL
          value: drupal-mysql
        - name: WORDPRESS_DB_HOST
          value: drupal-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: drupal
        volumeMounts:
        - name: drupal-files-volume
          mountPath: /var/www/html
      volumes:
      - name: drupal-files-volume
        persistentVolumeClaim:
          claimName: drupal-files-volume-claim


