apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-public-files
  labels:
    app: {{ .Values.php.app | quote }}
    release: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.php.publicFiles.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.php.publicFiles.storage }}
---
{{- if .Values.php.privateFiles.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-private-files
  labels:
    app: {{ .Values.php.app | quote }}
    release: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.php.privateFiles.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.php.privateFiles.storage }}
{{- end }}