apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "drupal.full_name" . }}-mysql-volume-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "drupal.full_name" . }}-files-volume-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi