apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-drupal
  labels:
    app: drupal
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: drupal
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        release: {{ .Release.Name }}
    spec:
      containers:
      # php-fpm container.
      - name: drupal
        {{ include "drupal.php-container" . | indent 8}}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - drush status
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - drush status
          initialDelaySeconds: 10
          periodSeconds: 15
      # Nginx container
      - name: nginx
        image: {{ .Values.nginx.image | quote }}
        resources:
          requests:
            cpu: "50m"
        env:
        - name: NGINX_STATIC_CONTENT_OPEN_FILE_CACHE
          value: "off"
        - name: NGINX_ERROR_LOG_LEVEL
          value: debug
        - name: NGINX_BACKEND_HOST
          value: localhost
        - name: NGINX_SERVER_ROOT
          value: /var/www/html/web
        ports:
        - containerPort: 80
          name: drupal
        volumeMounts:
        - name: drupal-public-files
          mountPath: /var/www/html/web/sites/default/files

      volumes:
        {{ include "drupal.volumes" . | indent 8}}

      {{ include "drupal.imagePullSecrets" . | indent 6 }}
