apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-drupal
  labels:
    release: "{{ .Release.Name }}"
type: Opaque
data:
  {{- if .Values.drupal.hashsalt }}
  hashsalt: "{{ .Values.drupal.hashsalt | b64enc }}"
  {{ else }}
  hashsalt: {{ "{{ randAlphaNum 10 }}" | b64enc }}
  {{- end }}
  {{- if .Values.nginx.basicauth.enabled }}
  .htaccess: | 
    {{ .Values.nginx.htaccess | b64enc }}
  {{- end }}