apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-public-files
  labels:
    name: {{ .Release.Name }}-public-files
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.publicFiles.storage }}
  storageClassName: {{ .Values.publicFiles.storageClassName }}
  {{- if .Values.publicFiles.csiDriverName }}
  csi:
    driver: {{ .Values.publicFiles.csiDriverName }}
    volumeHandle: data-id
    volumeAttributes:
      #   remote: "s3"
      #  remotePath: "projectname/pvname"
      remotePathSuffix: /{{ .Release.Name }}-public-files
    #   s3-provider: "Minio"
    #   s3-endpoint: "http://minio-release.default:9000"
    #   s3-access-key-id: "AKIAIOSFODNN7EXAMPLE"
    #   s3-secret-access-key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    #   dir-cache-time: 1s
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-public-files
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.publicFiles.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.publicFiles.storage }}
---
{{- if .Values.privateFiles.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-private-files
  labels:
    app: {{ .Values.app | quote }}
    release: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.privateFiles.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.privateFiles.storage }}
{{- end }}
---
{{- if .Values.referenceData.enabled }}
{{- if eq .Values.referenceData.referenceEnvironment .Values.environmentName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "drupal.referenceEnvironment" . }}-reference-data
  labels:
    app: {{ .Values.app | quote }}
    release: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.referenceData.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.referenceData.storage }}
{{- end }}
{{- end }}
---
{{- if .Values.shell.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-shell-keys
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
{{- end }}