apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-drupal
  labels:
    app: drupal
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: drupal
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        release: {{ .Release.Name }}
    spec:
      containers:
      # php-fpm container.
      - name: drupal
        image: {{ .Values.drupal.image | quote }}
        env:
        {{ include "drupal.env" . | indent 4 }}
        ports:
        - containerPort: 9000
          name: drupal
        volumeMounts:
        - name: drupal-public-files
          mountPath: /var/www/html/web/sites/default/files
        {{- if .Values.drupal.privateFiles.enabled }}
        - name: drupal-private-files
          mountPath: /var/www/html/private
        {{- end }}

      # Nginx container
      - name: nginx
        image: {{ .Values.nginx.image | quote }}
        resources:
          requests:
            cpu: "50m"
        env:
        - name: NGINX_STATIC_CONTENT_OPEN_FILE_CACHE
          value: "off"
        - name: NGINX_ERROR_LOG_LEVEL
          value: debug
        - name: NGINX_BACKEND_HOST
          value: localhost
        - name: NGINX_SERVER_ROOT
          value: /var/www/html/web
        ports:
        - containerPort: 80
          name: drupal
        volumeMounts:
        - name: drupal-public-files
          mountPath: /var/www/html/web/sites/default/files

      imagePullSecrets:
      - name: gcr
      volumes:
      - name: drupal-public-files
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-public-files
      {{- if .Values.drupal.privateFiles.enabled }}
      - name: drupal-private-files
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-private-files
      {{- end }}
