apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-drupal
  labels:
    app: {{ .Values.php.app | quote }}
    release: {{ .Release.Name }}
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  {{ .Release.Name }}-drupal
      host: {{ template "drupal.domain" . }}
      prefix: /
      service: {{ .Release.Name }}-drupal.{{ .Release.Namespace }}.svc.cluster.local:80
      timeout_ms: 30000
    domain: {{ template "drupal.domain" . }}
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: {{ .Values.php.app | quote }}
    release: {{ .Release.Name }}