apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets-drupal
  labels:
    release: "{{ .Release.Name }}"
type: Opaque
data:
  {{- if .Values.php.hashsalt }}
  hashsalt: "{{ .Values.php.hashsalt | b64enc }}"
  {{ else }}
  hashsalt: {{ "{{ randAlphaNum 10 }}" | b64enc }}
  {{- end }}