apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: elastic
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    run: elastic
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: elastic
  name: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      run: elastic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: elastic
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
        name: elastic
        ports:
        - containerPort: 9200
        resources: {}
        env:
          - name: discovery.type
            value: single-node
status: {}
