{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-elastic
  labels:
    {{ include "elastic.release_labels" . | indent 6 }}
spec:
  type: NodePort
  ports:
  - name: elastic
    port: 9200
  selector:
    {{ include "elastic.release_labels" . | indent 6 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-elastic
  labels:
    {{ include "elastic.release_labels" . | indent 6 }}
spec:
  selector:
    matchLabels:
      {{ include "elastic.release_labels" . | indent 8 }}
  template:
    metadata:
      labels:
        {{ include "elastic.release_labels" . | indent 10 }}
    spec:
      initContainers:
      # Refer to https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
      # and https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html#mlockall
      - name: increase-max-map-count
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: chown-data-volume-as-elastic
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "chown -R 1000:100 /usr/share/elasticsearch/data"]
        volumeMounts:
        - name: {{ .Release.Name }}-elastic-volume
          mountPath: "/usr/share/elasticsearch/data"
      #Allows ES container to disable swapping for performance boost
      #http://man7.org/linux/man-pages/man7/capabilities.7.html
      #https://github.com/kubernetes/kubernetes/issues/3595#issuecomment-423253874
      securityContext:
        fsGroup: 1000
        capabilities:
          add:
            - IPC_LOCK
            - SYS_RESOURCE
      containers:
      - name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:{{ .Values.elasticsearch.version }}
        ports:
        - containerPort: 9200
        resources:
          requests:
            memory: {{ .Values.elasticsearch.requests.memory }}
            cpu: {{ .Values.elasticsearch.requests.cpu }}
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: 9200
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 10
        env:
        - name: discovery.type
          value: single-node
        - name: cluster.name
          value: {{ .Release.Name }}-search
        - name: ES_JAVA_OPTS
          value: -Xms{{ .Values.elasticsearch.requests.heapSize }} -Xmx{{ .Values.elasticsearch.requests.heapSize }}
        volumeMounts:
        - mountPath: "/usr/share/elasticsearch/data"
          name: {{ .Release.Name }}-elastic-volume
      restartPolicy: Always
      volumes:
      - name: {{ .Release.Name }}-elastic-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-elastic-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-elastic-data
  labels:
    app: {{ .Values.app | quote }}
    release: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.elasticsearch.persistence.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.elasticsearch.persistence.size }}
{{- end }}
