apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-elastic
  labels:
    {{ include "elastic.release_labels" . | indent 6 }}
spec:
  type: NodePort
  ports:
  - name: elastic
    port: 9200
  selector:
    {{ include "elastic.release_labels" . | indent 6 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-elastic
  labels:
    {{ include "elastic.release_labels" . | indent 6 }}
spec:
  selector:
    matchLabels:
      {{ include "elastic.release_labels" . | indent 8 }}
  template:
    metadata:
      labels:
        {{ include "elastic.release_labels" . | indent 10 }}
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
        name: elastic
        ports:
        - containerPort: 9200
        resources:
          requests:
            cpu: "50m"
        env:
          - name: discovery.type
            value: single-node
        volumeMounts:
          - mountPath: "/usr/share/elasticsearch/data"
            name: {{ .Release.Name }}-elastic-volume
      volumes:
        - name: {{ .Release.Name }}-elastic-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-elastic-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-elastic-data
  labels:
    app: {{ .Values.app | quote }}
    release: {{ .Release.Name }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi