apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-drupal-frontend
  labels:
    app: drupal
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 80
  selector:
    app: drupal
    tier: frontend
    release: {{ .Release.Name }}
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}-drupal-frontend
  labels:
    app: drupal
spec:
  selector:
    matchLabels:
      app: drupal
      tier: frontend
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        tier: frontend
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
        name: nginx
        env:
        - name: NGINX_STATIC_CONTENT_OPEN_FILE_CACHE
          value: "off"
        - name: NGINX_ERROR_LOG_LEVEL
          value: debug
        - name: NGINX_BACKEND_HOST
          value: {{ .Release.Name }}-drupal
        - name: NGINX_SERVER_ROOT
          value: /var/www/html/web
        ports:
        - containerPort: 80
          name: drupal
        volumeMounts:
        - name: drupal-files-volume
          mountPath: /var/www/html/web/sites/default/files
      imagePullSecrets:
      - name: gcr
      volumes:
      - name: drupal-files-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-public-files


