{{- if .Values.varnish.enabled }}

# TODO:
# + Pass headers for remote_addr correctly
# + test static resource caching and SESS passtrough
# + Admin port
# + Admin secret
# + PHP ENV with host, secret and admin port
# - Tests
# - Cache type = file + set size

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-varnish
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
    service: varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "drupal.release_labels" . | nindent 6 }}
      service: varnish
  template:
    metadata:
      labels:
        {{- include "drupal.release_labels" . | nindent 8 }}
        service: varnish
      annotations:
        # https://github.com/kubernetes/kubernetes/issues/22368
        checksum/config: {{ include (print $.Chart.Name "/templates/varnish-configmap-vcl.yaml") . | sha256sum }}
    #For pod updates, kill the current pod, stand up the new one
    strategy:
      type: Recreate
    spec:
      containers:
      - name: varnish
        image: wunderio/drupal-varnish:v0.1.3
        ports:
        - containerPort: 80
          name: web
        - containerPort: 6082
          name: admin
        env:
          # https://varnish-cache.org/docs/trunk/users-guide/storage-backends.html
          VARNISH_STORAGE_BACKEND: {{ .Values.varnish.storageBackend }}
        resources:
{{ .Values.varnish.resources | toYaml | indent 10 }}
        volumeMounts:
        - name: varnish-vcl
          mountPath: /etc/varnish/default.vcl # mount nginx-conf configmap volume to /etc/nginx
          readOnly: true
          subPath: default.vcl
        - name: varnish-secret
          mountPath: "/etc/varnish/secret"
          readOnly: 

      volumes:
        - name: varnish-vcl
          configMap:
            name: {{ .Release.Name }}-varnish-vcl
            items:
              - key: default.vcl
                path: default.vcl
        - name: varnish-secret
          secret:
            secretName: secret
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-varnish
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
    service: varnish
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: web
    port: 80
  - name: admin
    port: 6082 
  selector:
    {{- include "drupal.release_labels" . | nindent 4 }}
    service: varnish
{{- end }}
