{{- if .Values.varnish.enabled }}

# TODO: 
# - Secret
# - Admin port
# - PHP ENV with secret and admin port
# - Tests

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-varnish
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
    service: varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "drupal.release_labels" . | nindent 6 }}
      service: varnish
  template:
    metadata:
      labels:
        {{- include "drupal.release_labels" . | nindent 8 }}
        service: varnish
    #For pod updates, kill the current pod, stand up the new one
    strategy:
      type: Recreate
    spec:
      containers:
      - name: varnish
        image: varnish:6.0 #stable
        ports:
        - containerPort: 80
        #- containerPort: 9200
        # env:
          # VARNISH_BACKEND_HOST: {{ .Release.Name }}-drupal
          # VARNISH_BACKEND_PORT: 80
        resources:
{{ .Values.varnish.resources | toYaml | indent 10 }}
        volumeMounts:
        - name: varnish-vcl
          mountPath: /etc/varnish/default.vcl # mount nginx-conf configmap volume to /etc/nginx
          readOnly: true
          subPath: default.vcl

      volumes:
        - name: varnish-vcl
          configMap:
            name: {{ .Release.Name }}-varnish-vcl
            items:
              - key: default.vcl
                path: default.vcl
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-varnish
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
    service: varnish
  annotations:
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 80
  #- port: 9200
  selector:
    {{- include "drupal.release_labels" . | nindent 4 }}
    service: varnish
{{- end }}
