# Default networkPolicy restricting access by default.
{{- $params := mergeOverwrite . (dict "id" "default") -}}
{{ include "silta-release.networkPolicy" $params }}
---
# Allow access to drupal or varnish pods from the ingress in the silta-cluster namespace
{{- $id := "allow-ingress" -}}
{{- $podSelectors := dict "silta-ingress" "allow" -}}
{{- $allowSiltaCluster := dict "namespaceSelector" (dict "matchLabels" (dict "name" "silta-cluster")) -}}
{{- $allowLoadBalancer := dict "ipBlock" (dict "cidr" "35.191.0.0/16") -}}
{{- $from := list $allowSiltaCluster $allowLoadBalancer -}}
{{- $params := dict "id" $id "additionalPodSelectors" $podSelectors "from" $from -}}
{{ include "silta-release.networkPolicy" (merge $params . ) }}
---
# Iterate through exceptions
{{- range $index, $accessDefinition := .Values.ingressAccess -}}
{{- $podSelectors := $accessDefinition.additionalPodSelector -}}
{{- $from := $accessDefinition.from -}}
{{- $params := dict "id" $index "additionalPodSelectors" $podSelectors "from" $from -}}
{{ include "silta-release.networkPolicy" (merge $params $) }}
---
{{ end }}
