version: 2.1

orbs:
  silta: silta/silta@dev:master
  kaniko-publish: glenjamin/kaniko-publish@0.0.4

jobs:
  check_and_build_only:
    executor: kaniko-publish/kaniko
    steps:
      - checkout
      - kaniko-publish/check
      - kaniko-publish/build_and_push:
          deploy: false

workflows:
  version: 2
  commit:
    jobs:
      - check_and_build_only
      - silta/drupal-validate:
          name: validate
          post-validation:
            - run:
                name: Helm unit tests
                command: helm unittest ./chart

      - silta/drupal-build-deploy: &build-deploy
          name: build-deploy
          # Use a local chart during development.
          chart_name: "./chart"
          chart_repository: ""
          silta_config: silta/silta.yml
          codebase-build:
            - silta/drupal-composer-install
            - silta/npm-install-build
          pre-release:
            - run:
                name: Add elastic repo for elasticsearch
                command: helm repo add elastic https://helm.elastic.co
            - run:
                name: Build local helm dependencies
                command: helm dependency build ./chart
            - run:
                name: Dry-run helm install
                command: helm install --dry-run ./chart
          context: global_nonprod
          filters:
            branches:
              ignore: production

      - silta/drupal-build-deploy:
          # Extend the build-deploy configuration for the production environment.
          <<: *build-deploy
          name: build-deploy-prod
          silta_config: silta/silta.yml,silta/silta-prod.yml
          context: global_nonprod
          filters:
            branches:
              only: production
