apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-drupal
  annotations:
    auto-downscale/down: "false"
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"ports": {"80":"{{ .Release.Name }}"}}'
spec:
  type: NodePort
  externalTrafficPolicy: Local
  # We explicitly unset this, in case the application is currently downscaled.
  externalName: null
  ports:
    - port: 80
  selector:
    {{- include "drupal.release_labels" . | nindent 4 }}
    deployment: drupal
