{{ $context_ingress := (index .Values "silta-release").ingress.default }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-drupal
  annotations:
    kubernetes.io/ingress.class: traefik
    {{- if $context_ingress.tls.enabled }}
    {{- if eq $context_ingress.type "traefik" }}
    traefik.ingress.kubernetes.io/frontend-entry-points: "http,https"
    {{- end }}
    {{- if (index $context_ingress.tls "https-redirect") }}
    ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- else }}
    {{- if eq $context_ingress.type "traefik" }}
    traefik.ingress.kubernetes.io/frontend-entry-points: "http"
    {{- end }}
    {{- if (index $context_ingress.tls "https-redirect") }}
    ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- end }}
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
    {{- if (index .Values "silta-release").downscaler.enabled }}
    auto-downscale/last-update: {{ dateInZone "2006-01-02T15:04:05.999Z" (now) "UTC" }}
    auto-downscale/label-selector: "release={{ .Release.Name }}"
    auto-downscale/services: {{ include "drupal.servicename" . }}
    {{- end }}
spec:
  {{- if $context_ingress.tls.enabled }}
  tls:
  - secretName: {{ .Release.Name }}-tls
  {{- range $index, $prefix := .Values.domainPrefixes }}
  - secretName: {{ $.Release.Name }}-tls-p{{ $index }}
  {{- end }}
  {{- end }}
  rules:
  - host: {{ include "drupal.domain" . | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "drupal.servicename" . }}
          servicePort: 80
{{- range $index, $prefix := .Values.domainPrefixes }}
  - host: '{{ $prefix }}.{{ template "drupal.domain" $ }}'
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "drupal.servicename" $ }}
          servicePort: 80
{{- end }}
---