{{ $context_ingress := (index .Values "silta-release").ingress.default }}
{{ $context_tls := (index (index .Values "silta-release").tls "built-in") }}

{{- if $context_ingress.tls.enabled }}
{{- if has $context_tls.issuer (list "letsencrypt" "letsencrypt-staging") }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-crt
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  secretName: {{ .Release.Name }}-tls
  dnsNames:
  - {{ include "drupal.domain" . | quote }}
  {{- range $index, $prefix := .Values.domainPrefixes }}
  - '{{$prefix}}.{{ include "drupal.domain" $ }}'
  {{- end }}
  issuerRef:
    name: {{ $context_tls.issuer }}
    kind: ClusterIssuer
  acme:
    config:
      - http01:
          ingress: {{ .Release.Name }}-drupal
        domains:
          - {{ template "drupal.domain" . }}
          {{- range $index, $prefix := .Values.domainPrefixes }}
          - '{{$prefix}}.{{ include "drupal.domain" $ }}'
          {{- end }}

---

{{- else if eq $context_tls.issuer "selfsigned" }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-crt
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  secretName: {{ .Release.Name }}-tls
  duration: 2160h
  renewBefore: 150h 
  commonName: {{ template "drupal.domain" . }}
  dnsNames:
  - {{ template "drupal.domain" . }}
  {{- range $index, $prefix := .Values.domainPrefixes }}
  - '{{$prefix}}.{{ include "drupal.domain" $ }}'
  {{- end }}
  issuerRef:
    name: {{ $context_tls.issuer }}
    kind: ClusterIssuer
---

{{- else if eq $context_tls.issuer "custom" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.ca: {{ $context_tls.ca | b64enc }}
  tls.crt: {{ $context_tls.crt | b64enc }}
  tls.key: {{ $context_tls.key | b64enc }}
---
{{- end }}


{{- end }}